// Generated by livescript 1.3.1
(function(){
  var livescript;
  livescript = require('LiveScript');
  module.exports = function(file, data){
    return livescript.compile(data, {
      bare: true,
      header: false,
      filename: file
    });
  };
}).call(this);
